### PR TITLE
Update billing-how-to-change-credit-card.md

### PR DESCRIPTION
**Pull request by genlin**
Correct a translation issue:

"如果您在 90 天的保留期結束後需要移除信用卡或轉帳卡" this translation is wrong. It should be "如果您在 90 天的保留期結束前需要移除信用卡或轉帳卡"

### CODE REVIEW

**Comment by genlin** [comment]
#sign-off

**Comment by genlin** [comment]
@v-radelg Can you help to review this pull request?

**Comment by gosali** [comment]
Hi @genlin , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@genlin , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
